spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fdb_dev
    username: fdb_dev_user
    password: ham22gonG
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: createtables.sql
